
[[Defs]]
comment = '''
The code actually needs 4 bytes ram at this address for the command buffer.
In this case, the stack is elsewhere, set by the Astrocade BIOS
'''
RAMADDR = 0x4fce

[Code]
#--------------------------------------------------------------------------
# STARTUP Routines
#
# These are called once, and can be used do any target-specific
# initialization that is required
#
# On the Z80, it is split into two.  This is because startup1 is 
# usually place into a space-limited region.
# It's best to expand startup2 and leave startup1 alone.
#--------------------------------------------------------------------------
startup = '''
;
;       STARTUP CODE
;
STARTUP1:
;
;       Assume the stack and the interrupt states are
;       set up properly, by the Astrocade BIOS.
;       Comment out normal startup code
;
        ;DI                  ; Disable interrupts - we don't handle them
        ;LD      SP,RAMADDR  ; have to set valid SP
'''

#--------------------------------------------------------------------------
# EVERY Routine
# This is called regularly, every polling loop, and can be used do any 
# target-specific task that is required, such as hitting a watchdog
#--------------------------------------------------------------------------
every = '''
;
;       EVERY CODE
;
EVERY:
        IN	A,(0x10)    ; hit watchdog
        RET
'''

[Links]
#--------------------------------------------------------------------------
# ROM TEMPLATE - this defines the rom layout, and which kind of io
#--------------------------------------------------------------------------
template = "rom_templates/astrocde-cart_romio_2000_2k.toml"

