
[[Defs]]
# if you skip the comment entry here, 
# it will pick up the comment in the template
RAMADDR = 0xdff0

[Code]
NMI = '''
NMI:    JP      START       ; restart on test button press
'''

every = '''
;
;       EVERY CODE
;
EVERY:
        IN	A,(0x10)    ; hit watchdog
        RET
'''

[Links]
#--------------------------------------------------------------------------
# ROM TEMPLATE - this defines the rom layout, and which kind of io
#--------------------------------------------------------------------------
template = "rom_templates/z80_gorf-tether_0000_2k.toml"
