
[[Defs]]
# if you skip the comment entry here, 
# it will pick up the comment in the template
RAMADDR = 0x63f0

[Links]
#--------------------------------------------------------------------------
# ROM TEMPLATE - this defines the rom layout, and which kind of io
#--------------------------------------------------------------------------
template = "rom_templates/z80_romio_0000_2k.toml"
