
[[Param]]
name = 'RAMSTRT'
value = 0x0000

[Template]
#--------------------------------------------------------------------------
# ROM TEMPLATE - this defines the rom layout, and which kind of io
#--------------------------------------------------------------------------
file = "templates/6502_romio_f800_2k.toml"
