
[[Param]]
# if you skip the comment entry here, 
# it will pick up the comment in the template
name = 'RAMADDR'
value = 0xdff0

[Code]
NMI = '''
NMI:    JP      START       ; restart on test button press
'''

every = '''
;
;       EVERY CODE
;
EVERY:
        IN	A,(0x10)    ; hit watchdog
        RET
'''

[Template]
#--------------------------------------------------------------------------
# ROM TEMPLATE - this defines the rom layout, and which kind of io
#--------------------------------------------------------------------------
file = "templates/z80_gorf-tether_0000_2k.toml"
