
[[Param]]
# if you skip the comment entry here, 
# it will pick up the comment in the template
RAMADDR = 0xcff0

[Code]
start2 = '''
;
;       START CODE 2
;
START2:
        LD      A,0x81
        LD      HL,0xE000
        LD      (HL),A      ; blank the screen
        JP      INIT
'''

[Template]
#--------------------------------------------------------------------------
# ROM TEMPLATE - this defines the rom layout, and which kind of io
#--------------------------------------------------------------------------
file = "templates/z80_romio_0000_2k.toml"
