
[[Defs]]
comment = 'Start of chip memory mapping'
STRTADD = 0x2000

[[Defs]]
comment = '2K ROM'
ROMSIZE = 0x0800

[[Defs]]
comment = '''
The code actually needs 4 bytes ram at this address for the command buffer.
However, stack also starts here, and will grow down (towards 0) from this point.
So, we need some above and below this address.  I generally choose the
Top of RAM minus 16'''
RAMADDR = 0xfff0

[[Defs]]
comment = 'delay factor'
BIGDEL = 0x0180

[Code]
cartheader = '''
        .byte   0x55        ; cartridge header
        .word   0x0218      ; next menu item (first one)
        .word   TITLE       ; title pointer
        .word   START       ; start pointer
        
        ret                 ; rst8
        nop
        nop

        ret                 ; rst16
        nop
        nop
        
        ret                 ; rst24
        nop
        nop
        
        ret                 ; rst32
        nop
        nop
        
        ret                 ; rst40
        nop
        nop
        
        ret                 ; rst48
        nop
        nop
'''

#--------------------------------------------------------------------------
# TITLE DATA
#--------------------------------------------------------------------------
title = '''
TITLE:
        .asciz	"DEMON DEBUGGER"
'''

#--------------------------------------------------------------------------
# START Routine
#
# This is called once, and can be used do any target-specific
# initialization that is required
#--------------------------------------------------------------------------
start = '''
;
;       START CODE
;
START:
        DI                  ; Disable interrupts - we don't handle them
        LD      SP,RAMADDR  ; have to set valid SP
;       YOUR CODE CAN GO HERE
        JP      INIT
'''

#--------------------------------------------------------------------------
# EVERY Routine
# This is called regularly, every polling loop, and can be used do any 
# target-specific task that is required, such as hitting a watchdog
#--------------------------------------------------------------------------
every = '''
;
;       EVERY CODE
;
EVERY:
;       YOUR CODE CAN GO HERE
        RET
'''

[[Region]]
code  = [
    { link = "core/dd.def" }, 
    { link = "core/z80.def" },
    { link = "io/romio.def" } 
]

[[Region]]
#---------------------------------------------------
# On the Astrocade cart, the start address is 0x2000
#---------------------------------------------------
start = 'STRTADD'
end = 'IOADD'
code = [
    { insert = 'cartheader' },
    { insert = 'title' },
    { insert = 'start' },
    { link = 'core/z80_main.asm'},
    { insert = 'every'},
    { link = 'io/z80_romio.asm'}
]

[[Region]]
start = 'IOADD'
end   = 'IOEND'
code  = [
    { link = "io/romio_table.asm" }
]

[[Region]]    
start = 'IOEND'
end = 'ROMEND'
